_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "TwoStagePseudoLabWeakRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "FocalLoss"
    NUM_CLASSES: 10

Extra_ARCH: "ws_head"

SOLVER:
  CHECKPOINT_PERIOD: 5000
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (249990, 249995)
  MAX_ITER: 250000
  IMG_PER_BATCH_LABEL: 32
  IMG_PER_BATCH_UNLABEL: 32
  BASE_LR: 0.0025
DATALOADER:
  SUP_PERCENT: 10.0
  RANDOM_DATA_SEED: 1
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("object365_train",)
  TEST: ("object365_val",)
SEMISUPNET:
  Trainer: "rbteacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 40000
  EMA_KEEP_RATE: 0.999
  UNSUP_LOSS_WEIGHT: 3.0
TEST:
  EVAL_PERIOD: 3000